ol.proj.get("EPSG:4326").setExtent([1048671.378372, 855936.084347, 1068630.463666, 879441.455873]);
var wms_layers = [];
var format_idescmc_comunas_0 = new ol.format.GeoJSON();
var features_idescmc_comunas_0 = format_idescmc_comunas_0.readFeatures(json_idescmc_comunas_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_idescmc_comunas_0 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_idescmc_comunas_0.addFeatures(features_idescmc_comunas_0);var lyr_idescmc_comunas_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_idescmc_comunas_0, 
                style: style_idescmc_comunas_0,
    title: 'idesc:mc_comunas<br />\
    <img src="styles/legend/idescmc_comunas_0_0.png" /> Comuna 1<br />\
    <img src="styles/legend/idescmc_comunas_0_1.png" /> Comuna 10<br />\
    <img src="styles/legend/idescmc_comunas_0_2.png" /> Comuna 11<br />\
    <img src="styles/legend/idescmc_comunas_0_3.png" /> Comuna 12<br />\
    <img src="styles/legend/idescmc_comunas_0_4.png" /> Comuna 13<br />\
    <img src="styles/legend/idescmc_comunas_0_5.png" /> Comuna 14<br />\
    <img src="styles/legend/idescmc_comunas_0_6.png" /> Comuna 15<br />\
    <img src="styles/legend/idescmc_comunas_0_7.png" /> Comuna 16<br />\
    <img src="styles/legend/idescmc_comunas_0_8.png" /> Comuna 17<br />\
    <img src="styles/legend/idescmc_comunas_0_9.png" /> Comuna 18<br />\
    <img src="styles/legend/idescmc_comunas_0_10.png" /> Comuna 19<br />\
    <img src="styles/legend/idescmc_comunas_0_11.png" /> Comuna 2<br />\
    <img src="styles/legend/idescmc_comunas_0_12.png" /> Comuna 20<br />\
    <img src="styles/legend/idescmc_comunas_0_13.png" /> Comuna 21<br />\
    <img src="styles/legend/idescmc_comunas_0_14.png" /> Comuna 22<br />\
    <img src="styles/legend/idescmc_comunas_0_15.png" /> Comuna 3<br />\
    <img src="styles/legend/idescmc_comunas_0_16.png" /> Comuna 4<br />\
    <img src="styles/legend/idescmc_comunas_0_17.png" /> Comuna 5<br />\
    <img src="styles/legend/idescmc_comunas_0_18.png" /> Comuna 6<br />\
    <img src="styles/legend/idescmc_comunas_0_19.png" /> Comuna 7<br />\
    <img src="styles/legend/idescmc_comunas_0_20.png" /> Comuna 8<br />\
    <img src="styles/legend/idescmc_comunas_0_21.png" /> Comuna 9<br />\
    <img src="styles/legend/idescmc_comunas_0_22.png" /> <br />'
        });var format_idescmc_cuadrantes_mecal_1 = new ol.format.GeoJSON();
var features_idescmc_cuadrantes_mecal_1 = format_idescmc_cuadrantes_mecal_1.readFeatures(json_idescmc_cuadrantes_mecal_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_idescmc_cuadrantes_mecal_1 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_idescmc_cuadrantes_mecal_1.addFeatures(features_idescmc_cuadrantes_mecal_1);var lyr_idescmc_cuadrantes_mecal_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_idescmc_cuadrantes_mecal_1, 
                style: style_idescmc_cuadrantes_mecal_1,
    title: 'idesc:mc_cuadrantes_mecal<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_0.png" /> CAI  ALFONSO BONILLA  ARAGON<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_1.png" /> CAI  AMBIENTAL<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_2.png" /> CAI BELLA VISTA<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_3.png" /> CAI BOTANICO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_4.png" /> CAI CHARCO AZUL<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_5.png" /> CAI CHIPICHAPE<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_6.png" /> CAI CORTIJO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_7.png" /> CAI CRISTO REY<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_8.png" /> CAI GALERIAS<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_9.png" /> CAI LA MERCED<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_10.png" /> CAI LOMA DE LA CRUZ<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_11.png" /> CAI MANUELA BELTRAN<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_12.png" /> CAI METROPOLITANO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_13.png" /> CAI MOJICA<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_14.png" /> CAI NAPOLES<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_15.png" /> CAI OBRERO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_16.png" /> CAI PANAMERICANO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_17.png" /> CAI PASO DEL COMERCIO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_18.png" /> CAI PETAR<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_19.png" /> CAI PIZAMOS<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_20.png" /> CAI PLAZA NORTE<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_21.png" /> CAI PONDAJE<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_22.png" /> CAI POTRERO GRANDE<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_23.png" /> CAI PUERTAS DEL SOL<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_24.png" /> CAI SALOMIA<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_25.png" /> CAI SAN ANTONIO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_26.png" /> CAI SAN MARINO<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_27.png" /> CAI SAN NICOLAS<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_28.png" /> CAI VALLE DEL LILI<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_29.png" /> CAI VILLA DEL SUR<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_30.png" /> ESTACION GUABAL<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_31.png" /> ESTACION MUNICIPAL<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_32.png" /> ESTACION NUEVA FLORESTA<br />\
    <img src="styles/legend/idescmc_cuadrantes_mecal_1_33.png" /> ESTACION SAN FRANCISCO<br />'
        });var format_idescmc_barrios_2 = new ol.format.GeoJSON();
var features_idescmc_barrios_2 = format_idescmc_barrios_2.readFeatures(json_idescmc_barrios_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_idescmc_barrios_2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_idescmc_barrios_2.addFeatures(features_idescmc_barrios_2);var lyr_idescmc_barrios_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_idescmc_barrios_2, 
                style: style_idescmc_barrios_2,
    title: 'idesc:mc_barrios<br />\
    <img src="styles/legend/idescmc_barrios_2_0.png" /> 20 de Julio<br />\
    <img src="styles/legend/idescmc_barrios_2_1.png" /> 3 de Julio<br />\
    <img src="styles/legend/idescmc_barrios_2_2.png" /> Área en Desarrollo - Parque del Amor<br />\
    <img src="styles/legend/idescmc_barrios_2_3.png" /> Aguablanca<br />\
    <img src="styles/legend/idescmc_barrios_2_4.png" /> Aguacatal<br />\
    <img src="styles/legend/idescmc_barrios_2_5.png" /> Alameda<br />\
    <img src="styles/legend/idescmc_barrios_2_6.png" /> Alférez Real<br />\
    <img src="styles/legend/idescmc_barrios_2_7.png" /> Alfonso Barberena A.<br />\
    <img src="styles/legend/idescmc_barrios_2_8.png" /> Alfonso Bonilla Aragón<br />\
    <img src="styles/legend/idescmc_barrios_2_9.png" /> Alfonso Lopez I<br />\
    <img src="styles/legend/idescmc_barrios_2_10.png" /> Alfonso Lopez II<br />\
    <img src="styles/legend/idescmc_barrios_2_11.png" /> Alfonso Lopez III<br />\
    <img src="styles/legend/idescmc_barrios_2_12.png" /> Alirio Mora Beltrán<br />\
    <img src="styles/legend/idescmc_barrios_2_13.png" /> Alto Nápoles<br />\
    <img src="styles/legend/idescmc_barrios_2_14.png" /> Altos de Menga<br />\
    <img src="styles/legend/idescmc_barrios_2_15.png" /> Antonio Nariño<br />\
    <img src="styles/legend/idescmc_barrios_2_16.png" /> Aranjuez<br />\
    <img src="styles/legend/idescmc_barrios_2_17.png" /> Arboledas<br />\
    <img src="styles/legend/idescmc_barrios_2_18.png" /> Asturias<br />\
    <img src="styles/legend/idescmc_barrios_2_19.png" /> Atanasio Girardot<br />\
    <img src="styles/legend/idescmc_barrios_2_20.png" /> Barrio Obrero<br />\
    <img src="styles/legend/idescmc_barrios_2_21.png" /> Base Aérea<br />\
    <img src="styles/legend/idescmc_barrios_2_22.png" /> Belalcázar<br />\
    <img src="styles/legend/idescmc_barrios_2_23.png" /> Belén<br />\
    <img src="styles/legend/idescmc_barrios_2_24.png" /> Belisario Caicedo<br />\
    <img src="styles/legend/idescmc_barrios_2_25.png" /> Bellavista<br />\
    <img src="styles/legend/idescmc_barrios_2_26.png" /> Bello Horizonte<br />\
    <img src="styles/legend/idescmc_barrios_2_27.png" /> Benjamín Herrera<br />\
    <img src="styles/legend/idescmc_barrios_2_28.png" /> Bolivariano<br />\
    <img src="styles/legend/idescmc_barrios_2_29.png" /> Bosques del Limonar<br />\
    <img src="styles/legend/idescmc_barrios_2_30.png" /> Bretaña<br />\
    <img src="styles/legend/idescmc_barrios_2_31.png" /> Brisas de Los Alamos<br />\
    <img src="styles/legend/idescmc_barrios_2_32.png" /> Brisas de Mayo<br />\
    <img src="styles/legend/idescmc_barrios_2_33.png" /> Brisas del Limonar<br />\
    <img src="styles/legend/idescmc_barrios_2_34.png" /> Buenos Aires<br />\
    <img src="styles/legend/idescmc_barrios_2_35.png" /> Caldas<br />\
    <img src="styles/legend/idescmc_barrios_2_36.png" /> Calima<br />\
    <img src="styles/legend/idescmc_barrios_2_37.png" /> Calimio Desepaz<br />\
    <img src="styles/legend/idescmc_barrios_2_38.png" /> Calipso<br />\
    <img src="styles/legend/idescmc_barrios_2_39.png" /> Camino Real - Joaquin Borrero Sinisterra<br />\
    <img src="styles/legend/idescmc_barrios_2_40.png" /> Camino Real - Los Fundadores<br />\
    <img src="styles/legend/idescmc_barrios_2_41.png" /> Caney<br />\
    <img src="styles/legend/idescmc_barrios_2_42.png" /> Cañaveral<br />\
    <img src="styles/legend/idescmc_barrios_2_43.png" /> Cañaveralejo - Seguros Patria<br />\
    <img src="styles/legend/idescmc_barrios_2_44.png" /> Cañaverales - Los Samanes<br />\
    <img src="styles/legend/idescmc_barrios_2_45.png" /> Cementerio - Carabineros<br />\
    <img src="styles/legend/idescmc_barrios_2_46.png" /> Centenario<br />\
    <img src="styles/legend/idescmc_barrios_2_47.png" /> Champagnat<br />\
    <img src="styles/legend/idescmc_barrios_2_48.png" /> Chapinero<br />\
    <img src="styles/legend/idescmc_barrios_2_49.png" /> Charco Azul<br />\
    <img src="styles/legend/idescmc_barrios_2_50.png" /> Chiminangos I<br />\
    <img src="styles/legend/idescmc_barrios_2_51.png" /> Chiminangos II<br />\
    <img src="styles/legend/idescmc_barrios_2_52.png" /> Chipichape<br />\
    <img src="styles/legend/idescmc_barrios_2_53.png" /> Ciudad 2000<br />\
    <img src="styles/legend/idescmc_barrios_2_54.png" /> Ciudad Campestre<br />\
    <img src="styles/legend/idescmc_barrios_2_55.png" /> Ciudad Capri<br />\
    <img src="styles/legend/idescmc_barrios_2_56.png" /> Ciudad Córdoba<br />\
    <img src="styles/legend/idescmc_barrios_2_57.png" /> Ciudad de Los Alamos<br />\
    <img src="styles/legend/idescmc_barrios_2_58.png" /> Ciudad Talanga<br />\
    <img src="styles/legend/idescmc_barrios_2_59.png" /> Ciudad Universitaria<br />\
    <img src="styles/legend/idescmc_barrios_2_60.png" /> Ciudadela Comfandi<br />\
    <img src="styles/legend/idescmc_barrios_2_61.png" /> Ciudadela del Rio - CVC<br />\
    <img src="styles/legend/idescmc_barrios_2_62.png" /> Ciudadela Floralia<br />\
    <img src="styles/legend/idescmc_barrios_2_63.png" /> Ciudadela Pasoancho<br />\
    <img src="styles/legend/idescmc_barrios_2_64.png" /> Club Campestre<br />\
    <img src="styles/legend/idescmc_barrios_2_65.png" /> Colinas del Sur<br />\
    <img src="styles/legend/idescmc_barrios_2_66.png" /> Colseguros Andes<br />\
    <img src="styles/legend/idescmc_barrios_2_67.png" /> Compartir<br />\
    <img src="styles/legend/idescmc_barrios_2_68.png" /> Cristóbal Colón<br />\
    <img src="styles/legend/idescmc_barrios_2_69.png" /> Cuarteles de Nápoles<br />\
    <img src="styles/legend/idescmc_barrios_2_70.png" /> Cuarto de Legua - Guadalupe<br />\
    <img src="styles/legend/idescmc_barrios_2_71.png" /> Departamental<br />\
    <img src="styles/legend/idescmc_barrios_2_72.png" /> Desepaz Invicali<br />\
    <img src="styles/legend/idescmc_barrios_2_73.png" /> Doce de Octubre<br />\
    <img src="styles/legend/idescmc_barrios_2_74.png" /> Eduardo Santos<br />\
    <img src="styles/legend/idescmc_barrios_2_75.png" /> El Bosque<br />\
    <img src="styles/legend/idescmc_barrios_2_76.png" /> El Calvario<br />\
    <img src="styles/legend/idescmc_barrios_2_77.png" /> El Cedro<br />\
    <img src="styles/legend/idescmc_barrios_2_78.png" /> El Cortijo<br />\
    <img src="styles/legend/idescmc_barrios_2_79.png" /> El Diamante<br />\
    <img src="styles/legend/idescmc_barrios_2_80.png" /> El Dorado<br />\
    <img src="styles/legend/idescmc_barrios_2_81.png" /> El Gran Limonar<br />\
    <img src="styles/legend/idescmc_barrios_2_82.png" /> El Gran Limonar - Cataya<br />\
    <img src="styles/legend/idescmc_barrios_2_83.png" /> El Guabal<br />\
    <img src="styles/legend/idescmc_barrios_2_84.png" /> El Hoyo<br />\
    <img src="styles/legend/idescmc_barrios_2_85.png" /> El Ingenio<br />\
    <img src="styles/legend/idescmc_barrios_2_86.png" /> El Jardín<br />\
    <img src="styles/legend/idescmc_barrios_2_87.png" /> El Jordán<br />\
    <img src="styles/legend/idescmc_barrios_2_88.png" /> El Lido<br />\
    <img src="styles/legend/idescmc_barrios_2_89.png" /> El Limonar<br />\
    <img src="styles/legend/idescmc_barrios_2_90.png" /> El Morichal<br />\
    <img src="styles/legend/idescmc_barrios_2_91.png" /> El Mortiñal<br />\
    <img src="styles/legend/idescmc_barrios_2_92.png" /> El Nacional<br />\
    <img src="styles/legend/idescmc_barrios_2_93.png" /> El Paraíso<br />\
    <img src="styles/legend/idescmc_barrios_2_94.png" /> El Peñón<br />\
    <img src="styles/legend/idescmc_barrios_2_95.png" /> El Piloto<br />\
    <img src="styles/legend/idescmc_barrios_2_96.png" /> El Poblado I<br />\
    <img src="styles/legend/idescmc_barrios_2_97.png" /> El Poblado II<br />\
    <img src="styles/legend/idescmc_barrios_2_98.png" /> El Pondaje<br />\
    <img src="styles/legend/idescmc_barrios_2_99.png" /> El Prado<br />\
    <img src="styles/legend/idescmc_barrios_2_100.png" /> El Recuerdo<br />\
    <img src="styles/legend/idescmc_barrios_2_101.png" /> El Refugio<br />\
    <img src="styles/legend/idescmc_barrios_2_102.png" /> El Remanso<br />\
    <img src="styles/legend/idescmc_barrios_2_103.png" /> El Retiro<br />\
    <img src="styles/legend/idescmc_barrios_2_104.png" /> El Rodeo<br />\
    <img src="styles/legend/idescmc_barrios_2_105.png" /> El Sena<br />\
    <img src="styles/legend/idescmc_barrios_2_106.png" /> El Trébol<br />\
    <img src="styles/legend/idescmc_barrios_2_107.png" /> El Troncal<br />\
    <img src="styles/legend/idescmc_barrios_2_108.png" /> El Vallado<br />\
    <img src="styles/legend/idescmc_barrios_2_109.png" /> El Vergel<br />\
    <img src="styles/legend/idescmc_barrios_2_110.png" /> Eucaristico<br />\
    <img src="styles/legend/idescmc_barrios_2_111.png" /> Evaristo Garcia<br />\
    <img src="styles/legend/idescmc_barrios_2_112.png" /> Fátima<br />\
    <img src="styles/legend/idescmc_barrios_2_113.png" /> Fenalco Kennedy<br />\
    <img src="styles/legend/idescmc_barrios_2_114.png" /> Fepicol<br />\
    <img src="styles/legend/idescmc_barrios_2_115.png" /> Flora Industrial<br />\
    <img src="styles/legend/idescmc_barrios_2_116.png" /> Fonaviemcali<br />\
    <img src="styles/legend/idescmc_barrios_2_117.png" /> Francisco Eladio Ramírez<br />\
    <img src="styles/legend/idescmc_barrios_2_118.png" /> Granada<br />\
    <img src="styles/legend/idescmc_barrios_2_119.png" /> Guayaquil<br />\
    <img src="styles/legend/idescmc_barrios_2_120.png" /> Guillermo Valencia<br />\
    <img src="styles/legend/idescmc_barrios_2_121.png" /> Horizontes<br />\
    <img src="styles/legend/idescmc_barrios_2_122.png" /> Ignacio Rengifo<br />\
    <img src="styles/legend/idescmc_barrios_2_123.png" /> Industria de Licores<br />\
    <img src="styles/legend/idescmc_barrios_2_124.png" /> Industrial<br />\
    <img src="styles/legend/idescmc_barrios_2_125.png" /> Jorge Eliécer Gaitán<br />\
    <img src="styles/legend/idescmc_barrios_2_126.png" /> Jorge Isaacs<br />\
    <img src="styles/legend/idescmc_barrios_2_127.png" /> Jorge Zawadsky<br />\
    <img src="styles/legend/idescmc_barrios_2_128.png" /> José Holguín Garcés<br />\
    <img src="styles/legend/idescmc_barrios_2_129.png" /> José Manuel Marroquín I<br />\
    <img src="styles/legend/idescmc_barrios_2_130.png" /> José Manuel Marroquín II<br />\
    <img src="styles/legend/idescmc_barrios_2_131.png" /> José María Córdoba<br />\
    <img src="styles/legend/idescmc_barrios_2_132.png" /> Juanambú<br />\
    <img src="styles/legend/idescmc_barrios_2_133.png" /> Julio Rincón<br />\
    <img src="styles/legend/idescmc_barrios_2_134.png" /> Junín<br />\
    <img src="styles/legend/idescmc_barrios_2_135.png" /> La Alborada<br />\
    <img src="styles/legend/idescmc_barrios_2_136.png" /> La Alianza<br />\
    <img src="styles/legend/idescmc_barrios_2_137.png" /> La Base<br />\
    <img src="styles/legend/idescmc_barrios_2_138.png" /> La Campiña<br />\
    <img src="styles/legend/idescmc_barrios_2_139.png" /> La Cascada<br />\
    <img src="styles/legend/idescmc_barrios_2_140.png" /> La Esmeralda<br />\
    <img src="styles/legend/idescmc_barrios_2_141.png" /> La Esperanza<br />\
    <img src="styles/legend/idescmc_barrios_2_142.png" /> La Flora<br />\
    <img src="styles/legend/idescmc_barrios_2_143.png" /> La Floresta<br />\
    <img src="styles/legend/idescmc_barrios_2_144.png" /> La Fortaleza<br />\
    <img src="styles/legend/idescmc_barrios_2_145.png" /> La Gran Colombia<br />\
    <img src="styles/legend/idescmc_barrios_2_146.png" /> La Hacienda<br />\
    <img src="styles/legend/idescmc_barrios_2_147.png" /> La Independencia<br />\
    <img src="styles/legend/idescmc_barrios_2_148.png" /> La Isla<br />\
    <img src="styles/legend/idescmc_barrios_2_149.png" /> La Libertad<br />\
    <img src="styles/legend/idescmc_barrios_2_150.png" /> La Merced<br />\
    <img src="styles/legend/idescmc_barrios_2_151.png" /> La Paz<br />\
    <img src="styles/legend/idescmc_barrios_2_152.png" /> La Playa<br />\
    <img src="styles/legend/idescmc_barrios_2_153.png" /> La Rivera I<br />\
    <img src="styles/legend/idescmc_barrios_2_154.png" /> La Selva<br />\
    <img src="styles/legend/idescmc_barrios_2_155.png" /> La Sultana<br />\
    <img src="styles/legend/idescmc_barrios_2_156.png" /> Las Acacias<br />\
    <img src="styles/legend/idescmc_barrios_2_157.png" /> Las Américas<br />\
    <img src="styles/legend/idescmc_barrios_2_158.png" /> Las Ceibas<br />\
    <img src="styles/legend/idescmc_barrios_2_159.png" /> Las Delicias<br />\
    <img src="styles/legend/idescmc_barrios_2_160.png" /> Las Granjas<br />\
    <img src="styles/legend/idescmc_barrios_2_161.png" /> Las Orquídeas<br />\
    <img src="styles/legend/idescmc_barrios_2_162.png" /> Las Quintas de Don Simón<br />\
    <img src="styles/legend/idescmc_barrios_2_163.png" /> Laureano Gómez<br />\
    <img src="styles/legend/idescmc_barrios_2_164.png" /> León XIII<br />\
    <img src="styles/legend/idescmc_barrios_2_165.png" /> Lili<br />\
    <img src="styles/legend/idescmc_barrios_2_166.png" /> Lleras Camargo<br />\
    <img src="styles/legend/idescmc_barrios_2_167.png" /> Lleras Restrepo<br />\
    <img src="styles/legend/idescmc_barrios_2_168.png" /> Lleras Restrepo II<br />\
    <img src="styles/legend/idescmc_barrios_2_169.png" /> Los Alcazares<br />\
    <img src="styles/legend/idescmc_barrios_2_170.png" /> Los Andes<br />\
    <img src="styles/legend/idescmc_barrios_2_171.png" /> Los Andes B - La Riviera<br />\
    <img src="styles/legend/idescmc_barrios_2_172.png" /> Los Cámbulos<br />\
    <img src="styles/legend/idescmc_barrios_2_173.png" /> Los Chorros<br />\
    <img src="styles/legend/idescmc_barrios_2_174.png" /> Los Comuneros I<br />\
    <img src="styles/legend/idescmc_barrios_2_175.png" /> Los Comuneros II<br />\
    <img src="styles/legend/idescmc_barrios_2_176.png" /> Los Conquistadores<br />\
    <img src="styles/legend/idescmc_barrios_2_177.png" /> Los Farallones<br />\
    <img src="styles/legend/idescmc_barrios_2_178.png" /> Los Guaduales<br />\
    <img src="styles/legend/idescmc_barrios_2_179.png" /> Los Guayacanes<br />\
    <img src="styles/legend/idescmc_barrios_2_180.png" /> Los Lagos<br />\
    <img src="styles/legend/idescmc_barrios_2_181.png" /> Los Libertadores<br />\
    <img src="styles/legend/idescmc_barrios_2_182.png" /> Los Lideres<br />\
    <img src="styles/legend/idescmc_barrios_2_183.png" /> Los Naranjos<br />\
    <img src="styles/legend/idescmc_barrios_2_184.png" /> Los Naranjos II<br />\
    <img src="styles/legend/idescmc_barrios_2_185.png" /> Los Parques Barranquilla<br />\
    <img src="styles/legend/idescmc_barrios_2_186.png" /> Los Pinos<br />\
    <img src="styles/legend/idescmc_barrios_2_187.png" /> Los Portales - Nuevo Rey<br />\
    <img src="styles/legend/idescmc_barrios_2_188.png" /> Los Robles<br />\
    <img src="styles/legend/idescmc_barrios_2_189.png" /> Los Sauces<br />\
    <img src="styles/legend/idescmc_barrios_2_190.png" /> Lourdes<br />\
    <img src="styles/legend/idescmc_barrios_2_191.png" /> Manuel Maria Buenaventura<br />\
    <img src="styles/legend/idescmc_barrios_2_192.png" /> Manuela Beltrán<br />\
    <img src="styles/legend/idescmc_barrios_2_193.png" /> Manzanares<br />\
    <img src="styles/legend/idescmc_barrios_2_194.png" /> Maracaibo<br />\
    <img src="styles/legend/idescmc_barrios_2_195.png" /> Marco Fidel Suárez<br />\
    <img src="styles/legend/idescmc_barrios_2_196.png" /> Mariano Ramos<br />\
    <img src="styles/legend/idescmc_barrios_2_197.png" /> Mario Correa Rengifo<br />\
    <img src="styles/legend/idescmc_barrios_2_198.png" /> Marroquín III<br />\
    <img src="styles/legend/idescmc_barrios_2_199.png" /> Mayapan - Las Vegas<br />\
    <img src="styles/legend/idescmc_barrios_2_200.png" /> Meléndez<br />\
    <img src="styles/legend/idescmc_barrios_2_201.png" /> Menga<br />\
    <img src="styles/legend/idescmc_barrios_2_202.png" /> Metropolitano del Norte<br />\
    <img src="styles/legend/idescmc_barrios_2_203.png" /> Miraflores<br />\
    <img src="styles/legend/idescmc_barrios_2_204.png" /> Mojica<br />\
    <img src="styles/legend/idescmc_barrios_2_205.png" /> Municipal<br />\
    <img src="styles/legend/idescmc_barrios_2_206.png" /> Nápoles<br />\
    <img src="styles/legend/idescmc_barrios_2_207.png" /> Navarro - La Chanca<br />\
    <img src="styles/legend/idescmc_barrios_2_208.png" /> Normandia<br />\
    <img src="styles/legend/idescmc_barrios_2_209.png" /> Nueva Floresta<br />\
    <img src="styles/legend/idescmc_barrios_2_210.png" /> Nueva Tequendama<br />\
    <img src="styles/legend/idescmc_barrios_2_211.png" /> Olaya Herrera<br />\
    <img src="styles/legend/idescmc_barrios_2_212.png" /> Olímpico<br />\
    <img src="styles/legend/idescmc_barrios_2_213.png" /> Omar Torrijos<br />\
    <img src="styles/legend/idescmc_barrios_2_214.png" /> Pampa Linda<br />\
    <img src="styles/legend/idescmc_barrios_2_215.png" /> Panamericano<br />\
    <img src="styles/legend/idescmc_barrios_2_216.png" /> Parcelaciones Pance<br />\
    <img src="styles/legend/idescmc_barrios_2_217.png" /> Parque de la Caña<br />\
    <img src="styles/legend/idescmc_barrios_2_218.png" /> Paseo de Los Almendros<br />\
    <img src="styles/legend/idescmc_barrios_2_219.png" /> Paso del Comercio<br />\
    <img src="styles/legend/idescmc_barrios_2_220.png" /> Pasoancho<br />\
    <img src="styles/legend/idescmc_barrios_2_221.png" /> Petecuy I<br />\
    <img src="styles/legend/idescmc_barrios_2_222.png" /> Petecuy II<br />\
    <img src="styles/legend/idescmc_barrios_2_223.png" /> Petecuy III<br />\
    <img src="styles/legend/idescmc_barrios_2_224.png" /> Pizamos I<br />\
    <img src="styles/legend/idescmc_barrios_2_225.png" /> Pizamos II<br />\
    <img src="styles/legend/idescmc_barrios_2_226.png" /> Pizamos III - Las Dalias<br />\
    <img src="styles/legend/idescmc_barrios_2_227.png" /> Planta de Tratamiento<br />\
    <img src="styles/legend/idescmc_barrios_2_228.png" /> Polvorines<br />\
    <img src="styles/legend/idescmc_barrios_2_229.png" /> Popular<br />\
    <img src="styles/legend/idescmc_barrios_2_230.png" /> Porvenir<br />\
    <img src="styles/legend/idescmc_barrios_2_231.png" /> Potrero Grande<br />\
    <img src="styles/legend/idescmc_barrios_2_232.png" /> Prados de Oriente<br />\
    <img src="styles/legend/idescmc_barrios_2_233.png" /> Prados del Limonar<br />\
    <img src="styles/legend/idescmc_barrios_2_234.png" /> Prados del Norte<br />\
    <img src="styles/legend/idescmc_barrios_2_235.png" /> Prados del Sur<br />\
    <img src="styles/legend/idescmc_barrios_2_236.png" /> Primavera<br />\
    <img src="styles/legend/idescmc_barrios_2_237.png" /> Primero de Mayo<br />\
    <img src="styles/legend/idescmc_barrios_2_238.png" /> Primitivo Crespo<br />\
    <img src="styles/legend/idescmc_barrios_2_239.png" /> Promociones Populares B<br />\
    <img src="styles/legend/idescmc_barrios_2_240.png" /> Pueblo Joven<br />\
    <img src="styles/legend/idescmc_barrios_2_241.png" /> Puerta del Sol<br />\
    <img src="styles/legend/idescmc_barrios_2_242.png" /> Puerto Mallarino<br />\
    <img src="styles/legend/idescmc_barrios_2_243.png" /> Puerto Nuevo<br />\
    <img src="styles/legend/idescmc_barrios_2_244.png" /> Rafael Uribe Uribe<br />\
    <img src="styles/legend/idescmc_barrios_2_245.png" /> República de Israel<br />\
    <img src="styles/legend/idescmc_barrios_2_246.png" /> Ricardo Balcázar<br />\
    <img src="styles/legend/idescmc_barrios_2_247.png" /> Rodrigo Lara Bonilla<br />\
    <img src="styles/legend/idescmc_barrios_2_248.png" /> Saavedra Galindo<br />\
    <img src="styles/legend/idescmc_barrios_2_249.png" /> Salomia<br />\
    <img src="styles/legend/idescmc_barrios_2_250.png" /> San Antonio<br />\
    <img src="styles/legend/idescmc_barrios_2_251.png" /> San Benito<br />\
    <img src="styles/legend/idescmc_barrios_2_252.png" /> San Carlos<br />\
    <img src="styles/legend/idescmc_barrios_2_253.png" /> San Cayetano<br />\
    <img src="styles/legend/idescmc_barrios_2_254.png" /> San Cristóbal<br />\
    <img src="styles/legend/idescmc_barrios_2_255.png" /> San Fernando Nuevo<br />\
    <img src="styles/legend/idescmc_barrios_2_256.png" /> San Fernando Viejo<br />\
    <img src="styles/legend/idescmc_barrios_2_257.png" /> San Juan Bosco<br />\
    <img src="styles/legend/idescmc_barrios_2_258.png" /> San Judas Tadeo I<br />\
    <img src="styles/legend/idescmc_barrios_2_259.png" /> San Judas Tadeo II<br />\
    <img src="styles/legend/idescmc_barrios_2_260.png" /> San Luis<br />\
    <img src="styles/legend/idescmc_barrios_2_261.png" /> San Luis II<br />\
    <img src="styles/legend/idescmc_barrios_2_262.png" /> San Marino<br />\
    <img src="styles/legend/idescmc_barrios_2_263.png" /> San Nicolás<br />\
    <img src="styles/legend/idescmc_barrios_2_264.png" /> San Pascual<br />\
    <img src="styles/legend/idescmc_barrios_2_265.png" /> San Pedro<br />\
    <img src="styles/legend/idescmc_barrios_2_266.png" /> San Pedro Claver<br />\
    <img src="styles/legend/idescmc_barrios_2_267.png" /> San Vicente<br />\
    <img src="styles/legend/idescmc_barrios_2_268.png" /> Santa Anita - La Selva<br />\
    <img src="styles/legend/idescmc_barrios_2_269.png" /> Santa Bárbara<br />\
    <img src="styles/legend/idescmc_barrios_2_270.png" /> Santa Elena<br />\
    <img src="styles/legend/idescmc_barrios_2_271.png" /> Santa Fé<br />\
    <img src="styles/legend/idescmc_barrios_2_272.png" /> Santa Isabel<br />\
    <img src="styles/legend/idescmc_barrios_2_273.png" /> Santa Mónica<br />\
    <img src="styles/legend/idescmc_barrios_2_274.png" /> Santa Mónica Belalcázar<br />\
    <img src="styles/legend/idescmc_barrios_2_275.png" /> Santa Mónica Popular<br />\
    <img src="styles/legend/idescmc_barrios_2_276.png" /> Santa Rita<br />\
    <img src="styles/legend/idescmc_barrios_2_277.png" /> Santa Rosa<br />\
    <img src="styles/legend/idescmc_barrios_2_278.png" /> Santa Teresita<br />\
    <img src="styles/legend/idescmc_barrios_2_279.png" /> Santander<br />\
    <img src="styles/legend/idescmc_barrios_2_280.png" /> Santo Domingo<br />\
    <img src="styles/legend/idescmc_barrios_2_281.png" /> Sector Alto de los Chorros<br />\
    <img src="styles/legend/idescmc_barrios_2_282.png" /> Sector Alto Jordán<br />\
    <img src="styles/legend/idescmc_barrios_2_283.png" /> Sector Altos de Normandia - Bataclán<br />\
    <img src="styles/legend/idescmc_barrios_2_284.png" /> Sector Altos de Santa Isabel<br />\
    <img src="styles/legend/idescmc_barrios_2_285.png" /> Sector Asprosocial - Diamante<br />\
    <img src="styles/legend/idescmc_barrios_2_286.png" /> Sector Bosque Municipal<br />\
    <img src="styles/legend/idescmc_barrios_2_287.png" /> Sector Cañaveralejo Guadalupe<br />\
    <img src="styles/legend/idescmc_barrios_2_288.png" /> Sector Laguna del Pondaje<br />\
    <img src="styles/legend/idescmc_barrios_2_289.png" /> Sector Meléndez<br />\
    <img src="styles/legend/idescmc_barrios_2_290.png" /> Sector Patio Bonito<br />\
    <img src="styles/legend/idescmc_barrios_2_291.png" /> Sector Puente del Comercio<br />\
    <img src="styles/legend/idescmc_barrios_2_292.png" /> Siete de Agosto<br />\
    <img src="styles/legend/idescmc_barrios_2_293.png" /> Siloé<br />\
    <img src="styles/legend/idescmc_barrios_2_294.png" /> Simón Bolívar<br />\
    <img src="styles/legend/idescmc_barrios_2_295.png" /> Sindical<br />\
    <img src="styles/legend/idescmc_barrios_2_296.png" /> Sucre<br />\
    <img src="styles/legend/idescmc_barrios_2_297.png" /> Sultana - Berlín - San Francisco<br />\
    <img src="styles/legend/idescmc_barrios_2_298.png" /> Tejares - Cristales<br />\
    <img src="styles/legend/idescmc_barrios_2_299.png" /> Terron Colorado<br />\
    <img src="styles/legend/idescmc_barrios_2_300.png" /> Tierra Blanca<br />\
    <img src="styles/legend/idescmc_barrios_2_301.png" /> Torres de Comfandi<br />\
    <img src="styles/legend/idescmc_barrios_2_302.png" /> U. D. A. Galindo Plaza de Toros<br />\
    <img src="styles/legend/idescmc_barrios_2_303.png" /> Ulpiano Lloreda<br />\
    <img src="styles/legend/idescmc_barrios_2_304.png" /> Unicentro Cali<br />\
    <img src="styles/legend/idescmc_barrios_2_305.png" /> Unidad Residencial Bueno Madrid<br />\
    <img src="styles/legend/idescmc_barrios_2_306.png" /> Unidad Residencial El Coliseo<br />\
    <img src="styles/legend/idescmc_barrios_2_307.png" /> Unidad Residencial Santiago de Cali<br />\
    <img src="styles/legend/idescmc_barrios_2_308.png" /> Unión de Vivienda Popular<br />\
    <img src="styles/legend/idescmc_barrios_2_309.png" /> Urbanización Boyaca<br />\
    <img src="styles/legend/idescmc_barrios_2_310.png" /> Urbanización Calimio<br />\
    <img src="styles/legend/idescmc_barrios_2_311.png" /> Urbanización Ciudad Jardín<br />\
    <img src="styles/legend/idescmc_barrios_2_312.png" /> Urbanización Colseguros<br />\
    <img src="styles/legend/idescmc_barrios_2_313.png" /> Urbanización El Angel del Hogar<br />\
    <img src="styles/legend/idescmc_barrios_2_314.png" /> Urbanización La Flora<br />\
    <img src="styles/legend/idescmc_barrios_2_315.png" /> Urbanización La Merced<br />\
    <img src="styles/legend/idescmc_barrios_2_316.png" /> Urbanización La Nueva Base<br />\
    <img src="styles/legend/idescmc_barrios_2_317.png" /> Urbanización Militar<br />\
    <img src="styles/legend/idescmc_barrios_2_318.png" /> Urbanización Nueva Granada<br />\
    <img src="styles/legend/idescmc_barrios_2_319.png" /> Urbanización Rio Lili<br />\
    <img src="styles/legend/idescmc_barrios_2_320.png" /> Urbanización San Joaquin<br />\
    <img src="styles/legend/idescmc_barrios_2_321.png" /> Urbanización Tequendama<br />\
    <img src="styles/legend/idescmc_barrios_2_322.png" /> Valle Grande<br />\
    <img src="styles/legend/idescmc_barrios_2_323.png" /> Venezuela - Urbanización Cañaveralejo<br />\
    <img src="styles/legend/idescmc_barrios_2_324.png" /> Versalles<br />\
    <img src="styles/legend/idescmc_barrios_2_325.png" /> Villa Colombia<br />\
    <img src="styles/legend/idescmc_barrios_2_326.png" /> Villa del Lago<br />\
    <img src="styles/legend/idescmc_barrios_2_327.png" /> Villa del Prado - El Guabito<br />\
    <img src="styles/legend/idescmc_barrios_2_328.png" /> Villa del Sol<br />\
    <img src="styles/legend/idescmc_barrios_2_329.png" /> Villa del Sur<br />\
    <img src="styles/legend/idescmc_barrios_2_330.png" /> Villablanca<br />\
    <img src="styles/legend/idescmc_barrios_2_331.png" /> Villamercedes I - Villa Luz - Las Garzas<br />\
    <img src="styles/legend/idescmc_barrios_2_332.png" /> Villanueva<br />\
    <img src="styles/legend/idescmc_barrios_2_333.png" /> Vipasa<br />\
    <img src="styles/legend/idescmc_barrios_2_334.png" /> Vista Hermosa<br />\
    <img src="styles/legend/idescmc_barrios_2_335.png" /> Yira Castro<br />\
    <img src="styles/legend/idescmc_barrios_2_336.png" /> <br />'
        });var format_pot_2014eqp_uco_salud_3 = new ol.format.GeoJSON();
var features_pot_2014eqp_uco_salud_3 = format_pot_2014eqp_uco_salud_3.readFeatures(json_pot_2014eqp_uco_salud_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_pot_2014eqp_uco_salud_3 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_pot_2014eqp_uco_salud_3.addFeatures(features_pot_2014eqp_uco_salud_3);var lyr_pot_2014eqp_uco_salud_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_pot_2014eqp_uco_salud_3, 
                style: style_pot_2014eqp_uco_salud_3,
    title: 'pot_2014:eqp_uco_salud<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_0.png" /> CLINICA "LOS ANDES"<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_1.png" /> CLINICA AMIGA COMFANDI<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_2.png" /> CLINICA BARRERAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_3.png" /> CLINICA BASILIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_4.png" /> CLINICA BURGOS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_5.png" /> CLINICA CALI NORTE SALUDCOOP<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_6.png" /> CLINICA CENTRO MEDICO  IMBANACO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_7.png" /> CLINICA CLINICENTRO COLSANITAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_8.png" /> CLINICA COMFANDI TEQUENDAMA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_9.png" /> CLINICA COMFENALCO (ANTIGUO HOSPITAL URIBE URIBE)<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_10.png" /> CLINICA DALI<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_11.png" /> CLINICA DE ALERGIAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_12.png" /> CLINICA DE ENDODONCIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_13.png" /> CLINICA DE FRACTURAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_14.png" /> CLINICA DE LA FAMILIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_15.png" /> CLINICA DE LA VISION DEL VALLE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_16.png" /> CLINICA DE LOS REMEDIOS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_17.png" /> CLINICA DE OCCIDENTE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_18.png" /> CLINICA DE OFTALMOLOGIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_19.png" /> CLINICA DE ORTODONCIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_20.png" /> CLINICA DE OTORRINOLARINGOLOGIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_21.png" /> CLINICA DE SONRISAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_22.png" /> CLINICA DEL COLON<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_23.png" /> CLINICA DEL ORIENTE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_24.png" /> CLINICA DEL PACIFICO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_25.png" /> CLINICA DEL SENO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_26.png" /> CLINICA DENTAL<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_27.png" /> CLINICA EL TREBOL<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_28.png" /> CLINICA ESTETICA DA VINCI<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_29.png" /> CLINICA FUNMEDICOS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_30.png" /> CLINICA GINECOLOGICA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_31.png" /> CLINICA INSTITUTO OCULAR DE OCCIDENTE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_32.png" /> CLINICA INTERPLASTICA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_33.png" /> CLINICA LA ESPERANZA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_34.png" /> CLINICA LOS ANGELES IPS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_35.png" /> CLINICA LUNGAVITA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_36.png" /> CLINICA MARACAIBO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_37.png" /> CLINICA MATERNO INFANTIL FARALLONES<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_38.png" /> CLINICA MATERNO INFANTIL LOS FARALLONES<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_39.png" /> CLINICA MEDICO QUIRÚRGICA DEL VALLE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_40.png" /> CLINICA NUESTRA SENORA DEL ROSARIO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_41.png" /> CLINICA ODONTOLOGICA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_42.png" /> CLINICA OFTALMOLOGICA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_43.png" /> CLINICA OFTAMOLOGICA DEL VALLE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_44.png" /> CLINICA ORIENTE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_45.png" /> CLINICA REGIONAL DE SANIDAD DE LA POLICIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_46.png" /> CLINICA REY DAVID<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_47.png" /> CLINICA SAN FERNANDO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_48.png" /> CLINICA SAN JOSE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_49.png" /> CLINICA SANITAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_50.png" /> CLINICA SANTA  ANITA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_51.png" /> CLINICA SANTIAGO DE CALI<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_52.png" /> CLINICA SANTILLANA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_53.png" /> CLINICA SEBASTIAN DE BELALCAZAR<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_54.png" /> CLINICA SIGMA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_55.png" /> CLINICA SUMMA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_56.png" /> CLINICA UNIDAD UROLOGICA RAMON Y CAJAL<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_57.png" /> CLINICA UROLOGICA SALUS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_58.png" /> CLINICA VALLE DEL LILI<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_59.png" /> CLINICA VERSALLE SAN MARCOS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_60.png" /> CLINICA VERSALLES<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_61.png" /> CLINICA VICTOR DE PORTILLO ODONTOLOGIA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_62.png" /> CLINICENTRO COLSANITAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_63.png" /> CLINICENTRO TEQUENDAMA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_64.png" /> HOSPITAL CAÑAVERALEJO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_65.png" /> HOSPITAL CARLOS CARMONA MONTOYA<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_66.png" /> HOSPITAL CARLOS HOLMES TRUJILLO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_67.png" /> HOSPITAL GERIATRICO ANCIANATO SAN MIGUEL<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_68.png" /> HOSPITAL INFANTIL NIÑO DIOS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_69.png" /> HOSPITAL ISAIAS DUARTE CANCINO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_70.png" /> HOSPITAL JOAQUIN PAZ BORRERO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_71.png" /> HOSPITAL MARIO CORREA RENGIFO<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_72.png" /> HOSPITAL MILITAR REGIONAL DE OCCIDENTE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_73.png" /> HOSPITAL PRIMITIVO IGLESIAS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_74.png" /> HOSPITAL SAN JUAN DE DIOS<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_75.png" /> HOSPITAL UNIVERSITARIO DEL VALLE<br />\
    <img src="styles/legend/pot_2014eqp_uco_salud_3_76.png" /> HOSPITAL UNIVERSITARIO PSIQUIATRICO SAN ISIDRO<br />'
        });

lyr_idescmc_comunas_0.setVisible(true);lyr_idescmc_cuadrantes_mecal_1.setVisible(true);lyr_idescmc_barrios_2.setVisible(true);lyr_pot_2014eqp_uco_salud_3.setVisible(true);
var layersList = [lyr_idescmc_comunas_0,lyr_idescmc_cuadrantes_mecal_1,lyr_idescmc_barrios_2,lyr_pot_2014eqp_uco_salud_3];
lyr_idescmc_comunas_0.set('fieldAliases', {'comuna': 'comuna', 'nombre': 'nombre', 'zona_recol': 'zona_recol', 'area': 'area', 'perimetro': 'perimetro', });
lyr_idescmc_cuadrantes_mecal_1.set('fieldAliases', {'id': 'id', 'cuadrante': 'cuadrante', 'no_cuadra': 'no_cuadra', 'estacion': 'estacion', 'cai': 'cai', 'id_distrit': 'id_distrit', 'distrito': 'distrito', 'telefono': 'telefono', 'municipio': 'municipio', });
lyr_idescmc_barrios_2.set('fieldAliases', {'id_barrio': 'id_barrio', 'barrio': 'barrio', 'comuna': 'comuna', 'estra_moda': 'estra_moda', 'area': 'area', 'perimetro': 'perimetro', });
lyr_pot_2014eqp_uco_salud_3.set('fieldAliases', {'nombre': 'nombre', 'localizaci': 'localizaci', 'servicio': 'servicio', 'nivel': 'nivel', 'propiedad': 'propiedad', 'tipos_de_e': 'tipos_de_e', 'categoria': 'categoria', 'escala': 'escala', 'permanenci': 'permanenci', 'estruc_eco': 'estruc_eco', });
lyr_idescmc_comunas_0.set('fieldImages', {'comuna': 'TextEdit', 'nombre': 'TextEdit', 'zona_recol': 'TextEdit', 'area': 'TextEdit', 'perimetro': 'TextEdit', });
lyr_idescmc_cuadrantes_mecal_1.set('fieldImages', {'id': 'TextEdit', 'cuadrante': 'TextEdit', 'no_cuadra': 'TextEdit', 'estacion': 'TextEdit', 'cai': 'TextEdit', 'id_distrit': 'TextEdit', 'distrito': 'TextEdit', 'telefono': 'TextEdit', 'municipio': 'TextEdit', });
lyr_idescmc_barrios_2.set('fieldImages', {'id_barrio': 'TextEdit', 'barrio': 'TextEdit', 'comuna': 'TextEdit', 'estra_moda': 'TextEdit', 'area': 'TextEdit', 'perimetro': 'TextEdit', });
lyr_pot_2014eqp_uco_salud_3.set('fieldImages', {'nombre': 'TextEdit', 'localizaci': 'TextEdit', 'servicio': 'TextEdit', 'nivel': 'TextEdit', 'propiedad': 'TextEdit', 'tipos_de_e': 'TextEdit', 'categoria': 'TextEdit', 'escala': 'TextEdit', 'permanenci': 'TextEdit', 'estruc_eco': 'TextEdit', });
lyr_idescmc_comunas_0.set('fieldLabels', {'comuna': 'header label', 'nombre': 'no label', 'zona_recol': 'no label', 'area': 'no label', 'perimetro': 'no label', });
lyr_idescmc_cuadrantes_mecal_1.set('fieldLabels', {'id': 'no label', 'cuadrante': 'no label', 'no_cuadra': 'no label', 'estacion': 'no label', 'cai': 'no label', 'id_distrit': 'no label', 'distrito': 'no label', 'telefono': 'no label', 'municipio': 'no label', });
lyr_idescmc_barrios_2.set('fieldLabels', {'id_barrio': 'no label', 'barrio': 'no label', 'comuna': 'no label', 'estra_moda': 'no label', 'area': 'no label', 'perimetro': 'no label', });
lyr_pot_2014eqp_uco_salud_3.set('fieldLabels', {'nombre': 'no label', 'localizaci': 'no label', 'servicio': 'no label', 'nivel': 'no label', 'propiedad': 'no label', 'tipos_de_e': 'no label', 'categoria': 'no label', 'escala': 'no label', 'permanenci': 'no label', 'estruc_eco': 'no label', });
lyr_pot_2014eqp_uco_salud_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});